name: sfm_logistic
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.19.1
  custom_refresh_indicator: ^4.0.1
  dio: ^5.9.0
  easy_stepper: ^0.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  go_router: ^16.2.4
  google_mlkit_text_recognition: ^0.15.0
  intl: ^0.20.2
  lottie: ^3.3.2
  pdf: ^3.11.3
  printing: ^5.14.2
  reactive_dropdown_search: ^6.0.0-pre4
  reactive_forms: ^18.1.1
  responsive_sizer: ^3.3.1
  syncfusion_flutter_datagrid: ^31.1.23
  toastification: ^3.0.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
